- programs/nftoken/src/account_types.rs
- programs/nftoken/src/ix_create_collection.rs
- programs/nftoken/src/ix_create_nft.rs
- programs/nftoken/src/lib.rs
- tests/nft-creation.test.ts
- tests/utils/create-collection.ts
- tests/utils/create-nft.ts
> Add created_at to collection

- .github/workflows/program-test.yml
Code from https://github.com/yourarj/solana-twitter-enhanced/blob/main/.github/workflows/rust.yml
Closes #16
> Set up GitHub Action to test Anchor Program on PRs

- programs/nftoken/src/account_types.rs
- programs/nftoken/src/ix_mintlist_create.rs
- programs/nftoken/src/ix_mintlist_mint_nft.rs
- programs/nftoken/src/ix_nft_create.rs
- tests/mintlist-add-mint-infos.test.ts
- tests/mintlist-creation.test.ts
- tests/mintlist-mint-nft.test.ts
- tests/utils/mintlist.ts
This is a small PR which is a bit nicer re types / ordering :)
> Rename `price` → `price_lamports`; update account orders

- programs/nftoken/src/ix_mintlist_mint_nft.rs
- programs/nftoken/src/ix_nft_create.rs
- tests/collection-create.test.ts
- tests/nft-create.test.ts
- tests/utils/create-nft.ts
> Allow setting holder when creating NFT

- Cargo.lock
- package.json
- programs/nftoken/Cargo.toml
- programs/nftoken/src/account_types.rs
- programs/nftoken/src/ix_collection_create.rs
- programs/nftoken/src/lib.rs
Crate — https://crates.io/crates/nftoken
Docs — https://docs.rs/nftoken/0.1.0/nftoken/
You can run `pnpm rustdocs:publish` to publish a new version to crates.io
Progress on #31
> Add configuration for rustdocs

- program-tests/collection-create.test.ts
- program-tests/collection-update.test.ts
- program-tests/mintlist-add-mint-infos.test.ts
- program-tests/mintlist-mint-nft.test.ts
- program-tests/nft-create.test.ts
- program-tests/nft-delegation.test.ts
- program-tests/nft-setup-creators.test.ts
- program-tests/set-nft-collection.test.ts
- program-tests/transfer-nft-ix.test.ts
- program-tests/utils/create-collection.ts
- program-tests/utils/create-nft.ts
- program-tests/utils/mintlist.ts
- programs/nftoken/Cargo.toml
- programs/nftoken/src/ix_mintlist_add_mint_infos.rs
- programs/nftoken/src/ix_mintlist_mint_nft.rs
- programs/nftoken/src/lib.rs
This also updates all math to use checked math.
> Add version to all instructions

- Anchor.toml
- package.json
- program-tests/utils/test-utils.ts
- programs/nftoken/src/lib.rs
This also deploys the NFT program to mainnet!
> Update deploy script and program ID

- docs/components/CreateNftSection.tsx
- docs/components/shell/SideNav.tsx
- docs/package.json
- pnpm-lock.yaml
So far, just the form for the interactive “Create NFT” section, without any interactivity. 
The image drop zone is hooked up to the file input, and can also be clicked to open a file picker. I was thinking that we might upload the image to S3 from the frontend, in which case we’d show the uploaded image in the UI via S3 URL (to give the user feedback that their image has successfully been added). 
https://user-images.githubusercontent.com/30215449/170793100-cb118a91-ff84-48da-96da-60c6d6b56636.mp4
> Create NFT Section

- docs/components/CodeBlock.tsx
- docs/markdoc/nodes.ts
- docs/package.json
- docs/pages/technical-details.md
- docs/public/globals.css
- pnpm-lock.yaml
Built out a code block component with click-to-copy that uses Prism to highlight code. We can also change the theme to [any of these](https://github.com/PrismJS/prism-themes#readme). 
(I’m very proud of the copy icon’s animation so I zoomed in for the video.)
https://user-images.githubusercontent.com/30215449/172715330-c7d277ba-d20f-4857-a192-282055e4f04e.mp4
> Add Code Blocks component

- docs/components/CreateNftSection.tsx
- docs/utils/api-client.ts
- docs/utils/upload-file.ts
Now when you create an NFT it'll use the image that you upload
> Hook up uploading image to creating NFT

- docs/components/CreateNftSection.tsx
Before:
https://user-images.githubusercontent.com/30215449/173958105-85bcd2c2-855e-4146-9093-fcce97f482a0.mp4
After: 
https://user-images.githubusercontent.com/30215449/173958116-942dc684-6661-4fa6-a297-1994e631a728.mp4
> Fix Create NFT responsiveness

- docs/components/CreateNftSection.tsx
- docs/pages/create-an-nft.md
- timeout the success state
- increase confetti
- improve docs
> Improve the create nft section

- docs/pages/_app.tsx
> Fix responsiveness issue due to code block 2

- docs/pages/index.tsx
[Video (2 mins)](https://share.cleanshot.com/WjuB2S)
> Mitigate layout shift due to splash page image

- docs/components/AttributeTable.tsx
- docs/markdoc/tags.ts
- docs/pages/technical-details.md
Adds a component with a nicer-looking table of attributes, which replaces the bulleted lists we had before.
> Attribute table

- docs/components/LuxModal.tsx
- docs/components/test/ModalTest.tsx
- docs/hooks/useIsMounted.ts
- docs/markdoc/tags.ts
- docs/package.json
- docs/pages/test/modal.md
- docs/styles/app.scss
- docs/utils/framer.ts
- pnpm-lock.yaml
Added a demo for the modal component here: https://nftoken-git-modal.luma-dev.com/test/modal
> Bring over LuxModal

- docs/package.json
- docs/pages/nft/[nftAddress].tsx
- docs/utils/NftokenFetcher.ts
- docs/utils/NftokenTypes.ts
- docs/utils/nft-borsh.ts
- docs/utils/rpc-types.ts
- pnpm-lock.yaml
> Add super basic page to see an NFT's information

- docs/pages/collection/[collectionAddress].tsx
- docs/pages/nft/[nftAddress].tsx
> Polish NFT and collection 404 pages

- docs/components/CreateMintlistSection.tsx
- docs/components/forms/ImageDropZone.tsx
- docs/pages/mintlist/[mintlistAddress].tsx
- docs/pages/mintlists.tsx
- docs/utils/NftokenFetcher.ts
- docs/utils/NftokenTypes.ts
- docs/utils/constants.ts
- docs/utils/nft-borsh.ts
Add the NFTs upload and grid sections to the `/mintlist/[mintlistAddress]` page
> Add the NFTs section to the Mintlist page

- docs/components/NftCard.tsx
- docs/hooks/useBoolean.ts
- docs/hooks/useCollectionNfts.ts
- docs/pages/collection/[collectionAddress].tsx
- docs/pages/mintlist/[mintlistAddress].tsx
- docs/utils/constants.ts
- docs/utils/nft-borsh.ts
Feature overview:
https://www.loom.com/share/22e0fe0f7f264529a719046d01d0d8a2
Extras:
- The nft card component used both on the mintlist and collection page has been extracted into the `NftCard` component. cc @benborgers 
QA:
You can use the following mintlist to test on devnet: https://nftoken-git-l-5182-allow-minting-from-mintlist.luma-dev.com/mintlist/heT9rmaXNQNttfwe5vPn6xymgEJg33cMDnNDGF6RuRo?network=devnet
> Allow Minting from Mintlist

- docs/components/DesktopSecondaryNav.tsx
- docs/components/PageLayout.tsx
- docs/pages/_app.tsx
It was being finnicky with position sticky
> Remove animation from secondary nav on desktop

- docs/components/CreateNftSection.tsx
I chose some photos from Unsplash that looked cool. Demo: https://nftoken-git-l-5357-give-suggestions-for-images-to-use-for.luma-dev.com/create-an-nft 
What do you think of the photos? 
I did Unsplash because the photos can be freely used, whereas I know for example DALL-E explicitly says you can’t use their art for NFTs.
> Give suggestions for images to use for NFT

- docs/next.config.js
Rewrite "/" to the Framer-hosted landing page
> Point nftoken.so to Framer-hosted landing page
